export const user = [
  {
    id: 1,
    firstName: "Tri",
    lastName: "Pham",
    workAt: "",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: 2,
    firstName: "Nhan",
    lastName: "Pham",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: 3,
    firstName: "Tai",
    lastName: "Pham",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: 4,
    firstName: "Quang",
    lastName: "Pham",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
  {
    id: 5,
    firstName: "Huy",
    lastName: "Pham",
    workAt: "mgm",
    school: "DTU",
    city: "Da Nang",
    country: "Viet Nam",
    address: "DTU",
  },
];
